#cloud-config

# Ensure that the locale is set
locale: "en_US.UTF-8"

# Update the package list and upgrade all packages
package_update: true
package_upgrade: true

# Add Kubernetes signing key and repository
runcmd:
  - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

apt:
  sources:
    kubernetes.list:
      source: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main"

# Install Docker and necessary packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - docker.io
  - containerd
  - docker-compose
  - socat
  - conntrack
  - kubeadm
  - kubelet
  - kubectl

package_hold:
  - kubeadm
  - kubelet
  - kubectl

# Kubernetes requires net.bridge.bridge-nf-call-iptables to be set to 1 in sysctl
write_files:
  - path: /etc/sysctl.d/90-k8s.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1

runcmd:
  # Reload sysctl to apply the bridge settings
  - sysctl --system

  # Enable and start Docker
  - systemctl enable docker
  - systemctl start docker

  # Disable swap in /etc/fstab
  - sed -i '/ swap / s/^/#/' /etc/fstab
  - swapoff -a

  # Make sure the kubelet uses the correct cgroup driver
  - echo "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd" > /etc/default/kubelet
  - systemctl daemon-reload
  - systemctl restart kubelet
